openapi: 3.1.0
info:
  title: "Forgot Password"
  description: "API for forgot password"
  version: "1.0.0"
paths:
  /auth/forgot-password:
    post:
      tags:
        - auth
      summary: "Generate a password reset token"
      operationId: forgotPassword
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "user@example.com"
      responses:
        '200':
          description: "Password reset token generated"
          content:
            application/json:
              example:
                reset_token: "jwt_token"
        '400':
          description: "Validation error"
          content:
            application/json:
              example:
                email: ["Not a valid email address."]
        '404':
          description: "Email not found"
          content:
            application/json:
              example:
                message: "Email not found"
