openapi: 3.1.0
info:
  title: "User Registration"
  description: "API for user registration"
  version: "1.0.0"
paths:
  /auth/register:
    post:
      summary: "Register a new user"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: "User registered successfully"
          content:
            application/json:
              example:
                message: "User registered successfully"
        '400':
          description: "Validation error"
          content:
            application/json:
              example:
                email: ['Not a valid email address.']
                password: ['Missing data for required field.']
