openapi: 3.1.0
info:
  title: "Reset Password"
  description: "API for resetting password"
  version: "1.0.0"
paths:
  /auth/reset-password:
    post:
      summary: "Reset user password"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                new_password:
                  type: string
      responses:
        '200':
          description: "Password reset successfully"
          content:
            application/json:
              example:
                message: "Password reset successfully"
        '400':
          description: "Validation error"
          content:
            application/json:
              example:
                token: ['Missing data for required field.']
                new_password: ['Missing data for required field.']
        '401':
          description: "Invalid token"
          content:
            application/json:
              example:
                message: "Invalid token"
        '500':
          description: "Server error"
          content:
            application/json:
              example:
                error: An error occurred
