openapi: 3.1.0
info:
  version: "1.0.0"
  title: "User Login API"
  description: "API for user login"
  license:
    name: "MIT"
    url: "https://opensource.org/licenses/MIT"
servers:
  - url: "http://localhost:5000"
paths:
  /auth/login:
    post:
      summary: "Login a user"
      operationId: loginUser
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "user@example.com"
                password:
                  type: string
                  example: "password123"
      responses:
        '200':
          description: "User logged in successfully"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
              example:
                access_token: "jwt_token"
                token_type: "bearer"
        '400':
          description: "Validation error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
              example:
                email: ["Not a valid email address."]
                password: ["Missing data for required field."]
        '401':
          description: "Invalid credentials"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                message: "Invalid credentials"
components:
  schemas:
    AuthResponse:
      type: object
      properties:
        access_token:
          type: string
        token_type:
          type: string
    ValidationError:
      type: object
      properties:
        email:
          type: array
          items:
            type: string
        password:
          type: array
          items:
            type: string
    Error:
      type: object
      properties:
        message:
          type: string
